<?php

// This file is automatically generated by Laravel...

return [
    App\Providers\AppServiceProvider::class,
    App\Providers\FolioServiceProvider::class,
    App\Providers\VoltServiceProvider::class,
];
